server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh_1
          #uri: http://localhost:8007
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/create/**
        - id: payment_routh_2
          #uri: http://localhost:8007
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**



eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
