server:
  port: 8005

spring:
  application:
    name: cloud-provider-service-consul

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}