server:
  port: 3344
spring:
  application:
    name: clou-config-center
  cloud:
    config:
      server:
        git:
          uri:
          search-paths:
            - springcloud-config
      label: master
