server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

    register-with-eureka: true
spring:
  application:
    name: cloud-order-service-hystrix


ribbon:
    ReadTimeout: 5000
    ConnectTimeout: 5000